spring:
  config:
    activate:
      on-profile: "local"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:~/poorlex
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
